

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - database
      - redis

  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ai_slides_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  studio:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    command: sh -c "npm install && npx prisma studio"
    depends_on:
      - database
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
